### ISSUE TITLE
404 with /xhr/shop/search

### ISSUE THREAD

**Issue by downquark** [bherrmann2/flight_finder#3]
I got this error when I ran FlightFinder.py last night which I am assuming is because the path /xhr/shop/search is no longer correct:

```
Enter the maximum trip length
14
l><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 NOT_FOUND</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: NOT_FOUND</h1>
</body></html>

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\python_2\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\m88852\code\flight_finder-master\flight_finder\ITADao.py", line 107, in run
    calendar = self.__get_calendar_data()
  File "C:\Users\m88852\code\flight_finder-master\flight_finder\ITADao.py", line 118, in __get_calendar_data
    data = json.loads(text)
  File "C:\python_2\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\python_2\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python_2\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by bherrmann2** [comment]
ITA recently released Matrix v3.0, so that is what probably broke it. I've been extremely busy with the holidays coming up and I'm going to be out of town, so feel free to fix it if you have time.
